apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.warehouse.database.deployment.name }}
  namespace: {{ .Values.warehouse.database.deployment.namespace }}
spec:
  selector:
    matchLabels:
      app: warehouse-db
  replicas: {{ .Values.warehouse.database.deployment.replicaCount }}
  template:
    metadata:
      labels:
        app: warehouse-db
    spec:
      containers:
      - name: couchdb
        image: "{{ .Values.warehouse.database.deployment.image.repository }}:{{ .Values.warehouse.database.deployment.image.tag }}"
        env:
        - name: COUCHDB_USER
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: username
        - name: COUCHDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: password
        - name: COUCH_HOST
          value: {{ .Values.warehouse.database.deployment.env.dbHost }}
        - name: COUCH_PORT
          value: {{ .Values.warehouse.database.deployment.env.dbPort }}
        ports:
        - containerPort: {{ .Values.warehouse.database.deployment.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.warehouse.database.service.name }}
  namespace: {{ .Values.warehouse.database.service.namespace }}
spec:
  ports:
  - port: {{ .Values.warehouse.database.service.port }}
  selector:
    app: warehouse-db
  type: {{ .Values.warehouse.database.service.type }}
  nodePort: {{ .Values.warehouse.database.service.nodePort }}