apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.deployment.namespace }}
  labels:
    app: warehouse-app
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: warehouse-app
  template:
    metadata:
      labels:
        app: warehouse-app
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.deployment.tag }}"
          env:
          - name: COUCHDB_USER
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: username
          - name: COUCHDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: password
          - name: COUCH_HOST
            value: "warehouse-db"
          - name: COUCH_PORT
            value: "5984"
          ports:
          - protocol: TCP
            containerPort: {{ .Values.deployment.port }}
            volumeMounts:
            - name: warehouse-app-storage
              mountPath: /var/www/html
          volumes:
          - name: warehouse-app-storage