apiVersion: v1
kind: Service
metadata:
  name: warehouse-app
  namespace: {{ .Values.service.namespace }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    nodePort: {{ .Values.service.nodePort }}
  selector:
    app: warehouse-app
  type: NodePort