apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.warehouse.application.deployment.name }}
  namespace: {{ .Values.warehouse.application.deployment.namespace }}
  labels:
    app: warehouse-app
spec:
  replicas: {{ .Values.warehouse.application.deployment.replicaCount }}
  selector:
    matchLabels:
      app: warehouse-app
  template:
    metadata:
      labels:
        app: warehouse-app
    spec:
      containers:
        - image: {{ .Values.warehouse.application.deployment.image.repository }}:{{ .Values.warehouse.application.deployment.image.tag }}
          name: {{ .Chart.Name }}
          env:
          - name: COUCHDB_USER
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: username
          - name: COUCHDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: password
          - name: COUCH_HOST
            value: "{{ .Values.warehouse.application.deployment.env.dbHost }}"
          - name: COUCH_PORT
            value: "{{ .Values.warehouse.application.deployment.env.dbPort }}"
          ports:
          - protocol: TCP
            containerPort: {{ .Values.warehouse.application.deployment.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.warehouse.application.service.name }}
  namespace: {{ .Values.warehouse.application.service.namespace }}
spec:
  ports:
  - port: {{ .Values.warehouse.application.service.port }}
    nodePort: {{ .Values.warehouse.application.service.nodePort }}
  selector:
    app: warehouse-app
  type: NodePort
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: warehouse-ingress
  namespace: {{ .Values.warehouse.application.service.namespace }}
spec:
  rules:
  - host: ware.app
    http:
      paths:
      - path: /
        backend:
          serviceName: app
          servicePort: 80